# Generated by Django 2.2.17 on 2021-03-12 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratemyrecipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratemyrecipeapp.UserProfile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratemyrecipeapp.Recipe')),
            ],
        ),
    ]
