# Generated by Django 2.2.17 on 2021-03-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemyrecipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
