# Generated by Django 2.2.17 on 2021-03-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemyrecipeapp', '0002_auto_20210312_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_needed',
            field=models.IntegerField(help_text='HH:MM:SS format'),
        ),
    ]
