# Generated by Django 2.2.17 on 2021-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemyrecipeapp', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='matchname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
