# Generated by Django 2.2.17 on 2021-03-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemyrecipeapp', '0003_category_matchname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='matchname',
        ),
    ]
