# Generated by Django 2.2.17 on 2021-03-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemyrecipeapp', '0004_remove_category_matchname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name_plural': 'recipes'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
