# Generated by Django 2.2.17 on 2021-04-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemyrecipeapp', '0006_auto_20210331_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, upload_to='recipe_images'),
        ),
    ]
