# Generated by Django 2.2.17 on 2021-04-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemyrecipeapp', '0009_auto_20210402_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_needed',
            field=models.CharField(max_length=5),
        ),
    ]
