# Generated by Django 2.2.17 on 2021-04-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemyrecipeapp', '0010_auto_20210403_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='', upload_to='recipe_images'),
            preserve_default=False,
        ),
    ]
